incorporate design feedback
DTS-STN/eligibility-estimator pull request #174
Opened 2022-02-15 17:46 UTC by KhalidAdan

WIP

2022-02-16 18:11 UTC, KhalidAdan commented on .npmrc
> +@dts-stn:registry=https://npm.pkg.github.com
remove

2022-02-16 18:14 UTC, KhalidAdan commented on components/Forms/ComponentFactory.tsx
> +                        onChange={debounce(field.handleChange, 300)}
I went with a 300ms debounce as it felt right, but let me know what you think. This solves the issue where you want to enter 65 as an age but when you hit 6 it already has an error on it

2022-02-16 21:46 UTC, JeremyKennedy reviewed
- I should have mentioned this earlier while I still had the chance, but I feel like the privacy notice should be merged into the original disclaimer. Oh well, this is fine too.
- Not in the changelog, but I see the Test Site header sizing is increased. Now, it is nearly the largest text on the screen, seems a little excessive now, and the alignment was better before:
![image](https://user-images.githubusercontent.com/3630698/154361196-b78eebcc-2194-4b53-82f3-3098cb52a0b1.png)
vs after:
![image](https://user-images.githubusercontent.com/3630698/154361290-619b6485-4ffb-45af-adce-344be6dff8ff.png)
- Not in the changelog, but I see you redesigned the tabs to be what is apparently not tabs and what is somehow more accessible? I don't get how this resolves the issues people raised, but it saves us from a bigger rewrite, so let's take it!
- I can confirm the questions are not bolded anymore. I liked it better before, because it made the questions stand out from the radio buttons (the radio text stands out more than the question text now).
- I see the outline colors have been updated, but not consistently for all components:
![image](https://user-images.githubusercontent.com/3630698/154361749-b8e7ffab-bed7-4ecd-9442-f4726705fcf9.png)
- I see the Need Help background is more of a muted color
- The 300 debounce works for me. Could argue increasing it to say, 500, but I don't think anyone will complain.
- The new results table estimated amount changes look good to me.
- The changes to the Application button look good as well.

2022-02-17 20:12 UTC, KhalidAdan commented
Alla and I spoke and a couple of things were fixed that you brought up, plus label changes to make the page feel less uniform and have the higher importance elements stand out a little more!

2022-02-17 20:29 UTC, JeremyKennedy requested changes
- :heavy_check_mark: I see the Test Site header is vertically aligned now, nice!
- :heavy_check_mark: I see the questions are back to bold, great!
- :question: I see the Progress Bar now has darker colors for the unchecked items. I think this makes it harder to visually differentiate between the checked and unchecked, because now the color is very similar. I think that should go back to before so the contrast between the two is higher.
Now:
![image](https://user-images.githubusercontent.com/3630698/154564214-32438b9a-c9be-4242-a5fd-b89d5147ee66.png)
Before:
![image](https://user-images.githubusercontent.com/3630698/154564237-e51a2355-3a27-4689-bb44-499c839eea58.png)
- :exclamation: The outline on TextBox vs Dropdown is still inconsistent, before the latter was lighter, now it is darker:
![image](https://user-images.githubusercontent.com/3630698/154564405-ef931ce2-b792-4ffc-abc4-8c72d7c27357.png)
- :question: I see the buttons have a heavier outline now, was this intended? It feels like it goes against the design system, but I don't have anything to back that up!
Now:
![image](https://user-images.githubusercontent.com/3630698/154564637-0a4d2690-a1a6-4a6e-a727-196904b37927.png)
Before:
![image](https://user-images.githubusercontent.com/3630698/154564662-bae8a673-d08e-4f59-9569-365fd1dfc844.png)

I think that is all the changes I've noticed since my last review, you didn't mention them specifically so I am unable to confirm specific changes.

I just have the two questions :question: above, then the inconsistent outline :exclamation:, then should be good to merge :heavy_check_mark:!

2022-02-17 20:36 UTC, KhalidAdan commented
> * ✔️ I see the Test Site header is vertically aligned now, nice!
> * ✔️ I see the questions are back to bold, great!
> * ❓ I see the Progress Bar now has darker colors for the unchecked items. I think this makes it harder to visually differentiate between the checked and unchecked, because now the color is very similar. I think that should go back to before so the contrast between the two is higher.
>   Now:
>   ![image](https://user-images.githubusercontent.com/3630698/154564214-32438b9a-c9be-4242-a5fd-b89d5147ee66.png)
>   Before:
>   ![image](https://user-images.githubusercontent.com/3630698/154564237-e51a2355-3a27-4689-bb44-499c839eea58.png)

The design system team has commented that the colours we have do not pass accessiblity checks, so Alla implemented these new ones.

> * ❗ The outline on TextBox vs Dropdown is still inconsistent, before the latter was lighter, now it is darker:
>   ![image](https://user-images.githubusercontent.com/3630698/154564405-ef931ce2-b792-4ffc-abc4-8c72d7c27357.png)

This is a good observation, for some reason though -- the border is thicker on `react-select` components, but I can confirm they are indeed the same colour (#333). I'll address this now.

> * ❓ I see the buttons have a heavier outline now, was this intended? It feels like it goes against the design system, but I don't have anything to back that up!
>   Now:
>   ![image](https://user-images.githubusercontent.com/3630698/154564637-0a4d2690-a1a6-4a6e-a727-196904b37927.png)
>   Before:
>   ![image](https://user-images.githubusercontent.com/3630698/154564662-bae8a673-d08e-4f59-9569-365fd1dfc844.png)
> 

Nope, just to heavy handed of a css variable and my browser extensions being too forgiving. Fixing now! I'll also start checking these in a private window with no extension.

> I think that is all the changes I've noticed since my last review, you didn't mention them specifically so I am unable to confirm specific changes.
> 
> I just have the two questions ❓ above, then the inconsistent outline ❗, then should be good to merge ✔️!

2022-02-17 21:46 UTC, JeremyKennedy approved these changes
The dropdown outline is fixed, the button outline is fixed, and I guess we're cool with the progress bar coloring being hard to differentiate visually, because it's more accessible somehow!

All good!

2022-02-17 21:46 UTC, merged