Bugfix/misc changes additions
DTS-STN/eligibility-estimator pull request #183
Opened 2022-02-24 17:04 UTC by KhalidAdan

2022-02-24 21:42 UTC, JeremyKennedy approved these changes
Looks great! I love easy-to-review PRs. All the diffs are straightforward, lots of quick wins here!

2022-02-24 21:42 UTC, JeremyKennedy commented on client-state/models/Form.ts
> +        console.log(data)
🤔

2022-02-24 21:43 UTC, JeremyKennedy requested changes
I take that back!!!

![image](https://user-images.githubusercontent.com/3630698/155612673-cbe9b089-b081-42ae-acd4-2f2ff6552c8a.png)

2022-02-25 14:01 UTC, KhalidAdan commented
Fixed! Think we could get this out today before EE testing? @JeremyKennedy

2022-02-25 14:56 UTC, JeremyKennedy approved these changes

2022-02-25 14:56 UTC, merged