131408 - change text and insert oasClawback before deferral
DTS-STN/eligibility-estimator pull request #807
Opened 2023-07-10 20:10 UTC by MarcoGoC

## [131408](https://dev.azure.com/VP-BD/DECD/_workitems/edit/131408) Change text & clawback message

### Description
- Change french and english text as requested
- Change the position of the clawback message before the deferral message and the deferral table

#### List of proposed changes:
- as above

### What to test for/How to test

### Additional Notes

2023-07-12 19:56 UTC, Maxim-Lam requested changes

2023-07-12 19:56 UTC, Maxim-Lam commented on i18n/api/fr.ts
> +      "Puisque votre revenu est plus grand que {OAS_RECOVERY_TAX_CUTOFF}, vous ne recevrez pas une une partie ou la totalité de votre pension de la Sécurité de la vieillesse en raison de l'{LINK_RECO
There is an extra "une" in here

2023-07-12 19:56 UTC, Maxim-Lam commented on i18n/api/fr.ts
> +      "Puisque votre revenu est plus grand que {OAS_RECOVERY_TAX_CUTOFF} et que vous vivez à l'extérieur du Canada, vous ne recevrez pas une une partie ou la totalité de votre pension de la Sécurité
here as well

2023-07-12 19:57 UTC, Maxim-Lam approved these changes
Good once changes implemented

2023-07-13 12:07 UTC, MarcoGoC commented on i18n/api/fr.ts
> +      "Puisque votre revenu est plus grand que {OAS_RECOVERY_TAX_CUTOFF}, vous ne recevrez pas une une partie ou la totalité de votre pension de la Sécurité de la vieillesse en raison de l'{LINK_RECO
good catch

2023-07-13 12:18 UTC, merged